In [1]:
import pandas as pd
import numpy as np

In [2]:
finance_info = pd.read_excel('./test/total.xlsx')

In [3]:
stock_info = pd.read_excel('./test/total_stock_price.xlsx')

In [4]:
finance_info

회사명   거래소코드     거래년월  [공통]자산(*)(IFRS)  [공통]자본(*)(IFRS)  \
0      (주)BNK금융지주  138930  2013/03     3.408280e+09     2.669557e+09   
1      (주)BNK금융지주  138930  2013/06     3.317116e+09     2.663748e+09   
2      (주)BNK금융지주  138930  2013/09     3.452216e+09     2.656921e+09   
3      (주)BNK금융지주  138930  2013/12     3.507652e+09     2.737860e+09   
4      (주)BNK금융지주  138930  2014/03     3.524501e+09     2.675315e+09   
5      (주)BNK금융지주  138930  2014/06     3.458675e+09     2.666645e+09   
6      (주)BNK금융지주  138930  2014/09     4.529620e+09     3.568822e+09   
7      (주)BNK금융지주  138930  2014/12     4.539500e+09     3.550847e+09   
8      (주)BNK금융지주  138930  2015/03     4.646373e+09     3.492415e+09   
9      (주)BNK금융지주  138930  2015/06     4.984864e+09     3.910631e+09   
10     (주)BNK금융지주  138930  2015/09     5.192447e+09     4.040897e+09   
11     (주)BNK금융지주  138930  2015/12     5.244360e+09     4.086109e+09   
12     (주)BNK금융지주  138930  2016/03     5.758504e+09     4.530530e+09   
13     (주)BNK금융지주  138930  2016/06     5.827788e+09     4.516512e+09   
14     (주)BNK금융지주  138930  2016/09     5.732888e+09     4.503713e+09   
15     (주)BNK금융지주  138930  2016/12     5.808094e+09     4.579364e+09   
16     (주)BNK금융지주  138930  2017/03     5.885458e+09     4.548121e+09   
17     (주)BNK금융지주  138930  2017/06     5.757054e+09     4.531952e+09   
18     (주)BNK금융지주  138930  2017/09     5.825496e+09     4.519910e+09   
19     (주)BNK금융지주  138930  2017/12     5.868329e+09     4.622231e+09   
20       (주)DB하이텍     990  2013/03     1.143783e+09     2.531924e+08   
21       (주)DB하이텍     990  2013/06     1.163972e+09     2.484604e+08   
22       (주)DB하이텍     990  2013/09     1.104651e+09     2.328288e+08   
23       (주)DB하이텍     990  2013/12     1.049495e+09     1.972875e+08   
24       (주)DB하이텍     990  2014/03     1.041779e+09     1.791741e+08   
25       (주)DB하이텍     990  2014/06     1.046430e+09     1.788359e+08   
26       (주)DB하이텍     990  2014/09     1.023040e+09     1.561305e+08   
27       (주)DB하이텍     990  2014/12     1.001960e+09     1.361041e+08   
28       (주)DB하이텍     990  2015/03     1.003405e+09     2.009092e+08   
29       (주)DB하이텍     990  2015/06     1.034293e+09     2.409391e+08   
...           ...     ...      ...              ...              ...   
3779  현대해상화재보험(주)    1450  2015/09     3.087031e+10     2.509813e+09   
3780  현대해상화재보험(주)    1450  2015/12     3.229161e+10     2.434663e+09   
3781  현대해상화재보험(주)    1450  2016/03     3.317129e+10     2.642345e+09   
3782  현대해상화재보험(주)    1450  2016/06     3.515955e+10     3.429597e+09   
3783  현대해상화재보험(주)    1450  2016/09     3.598293e+10     3.583422e+09   
3784  현대해상화재보험(주)    1450  2016/12     3.665224e+10     2.758116e+09   
3785  현대해상화재보험(주)    1450  2017/03     3.692660e+10     2.793910e+09   
3786  현대해상화재보험(주)    1450  2017/06     3.844214e+10     3.070665e+09   
3787  현대해상화재보험(주)    1450  2017/09     3.923677e+10     3.064774e+09   
3788  현대해상화재보험(주)    1450  2017/12     4.012213e+10     3.102685e+09   
3789       휴켐스(주)   69260  2013/03     7.916139e+08     4.442141e+08   
3790       휴켐스(주)   69260  2013/06     7.554658e+08     4.377150e+08   
3791       휴켐스(주)   69260  2013/09     7.170146e+08     4.527486e+08   
3792       휴켐스(주)   69260  2013/12     7.307698e+08     4.650071e+08   
3793       휴켐스(주)   69260  2014/03     7.190368e+08     4.516768e+08   
3794       휴켐스(주)   69260  2014/06     6.486685e+08     4.596332e+08   
3795       휴켐스(주)   69260  2014/09     6.785748e+08     4.692801e+08   
3796       휴켐스(주)   69260  2014/12     6.990655e+08     4.768318e+08   
3797       휴켐스(주)   69260  2015/03     6.685857e+08     4.697315e+08   
3798       휴켐스(주)   69260  2015/06     6.551989e+08     4.812022e+08   
3799       휴켐스(주)   69260  2015/09     7.163897e+08     4.854774e+08   
3800       휴켐스(주)   69260  2015/12     6.679840e+08     4.790227e+08   
3801       휴켐스(주)   69260  2016/03     6.430141e+08     4.629067e+08   
3802       휴켐스(주)   69260  2016/06     6.564630e+08   

In [5]:
stock_info

회사명   거래소코드     거래년월   최고가(원)   최저가(원)  산술평균(원)    종가(원)  \
0      (주)BNK금융지주  138930  2013/03  16900.0  14750.0  15400.0  15300.0   
1      (주)BNK금융지주  138930  2013/06  16200.0  13150.0  14616.0  14450.0   
2      (주)BNK금융지주  138930  2013/09  17000.0  14050.0  15550.0  16050.0   
3      (주)BNK금융지주  138930  2013/12  16500.0  14950.0  15663.0  16000.0   
4      (주)BNK금융지주  138930  2014/03  16050.0  14800.0  15357.0  15050.0   
5      (주)BNK금융지주  138930  2014/06  16100.0  14400.0  15282.0  14900.0   
6      (주)BNK금융지주  138930  2014/09  17850.0  16300.0  17266.0  16900.0   
7      (주)BNK금융지주  138930  2014/12  15900.0  14250.0  15114.0  14500.0   
8      (주)BNK금융지주  138930  2015/03  15600.0  14000.0  14807.0  15200.0   
9      (주)BNK금융지주  138930  2015/06  15750.0  13800.0  14566.0  14200.0   
10     (주)BNK금융지주  138930  2015/09  14200.0  13000.0  13615.0  13700.0   
11     (주)BNK금융지주  138930  2015/12   9700.0   8180.0   8716.0   8420.0   
12     (주)BNK금융지주  138930  2016/03   9700.0   8670.0   9263.0   9700.0   
13     (주)BNK금융지주  138930  2016/06   9220.0   7800.0   8500.0   8070.0   
14     (주)BNK금융지주  138930  2016/09   8990.0   8420.0   8720.0   8580.0   
15     (주)BNK금융지주  138930  2016/12   9240.0   8620.0   8937.0   8680.0   
16     (주)BNK금융지주  138930  2017/03   9530.0   8610.0   9115.0   9200.0   
17     (주)BNK금융지주  138930  2017/06  11050.0   9920.0  10567.0  10950.0   
18     (주)BNK금융지주  138930  2017/09  10350.0   9370.0   9942.0  10000.0   
19     (주)BNK금융지주  138930  2017/12   9740.0   9210.0   9405.0   9420.0   
20       (주)DB하이텍     990  2013/03   6960.0   6150.0   6557.0   6250.0   
21       (주)DB하이텍     990  2013/06   8980.0   6200.0   7506.0   6870.0   
22       (주)DB하이텍     990  2013/09   7040.0   6330.0   6753.0   6580.0   
23       (주)DB하이텍     990  2013/12   7970.0   4955.0   5506.0   7530.0   
24       (주)DB하이텍     990  2014/03   7330.0   6160.0   6691.0   6700.0   
25       (주)DB하이텍     990  2014/06   6110.0   3370.0   4888.0   3915.0   
26       (주)DB하이텍     990  2014/09   6400.0   5300.0   5668.0   5490.0   
27       (주)DB하이텍     990  2014/12   5740.0   4335.0   5003.0   4615.0   
28       (주)DB하이텍     990  2015/03   7400.0   5690.0   6527.0   5990.0   
29       (주)DB하이텍     990  2015/06  16550.0  12700.0  15214.0  15800.0   
...           ...     ...      ...      ...      ...      ...      ...   
3737  현대해상화재보험(주)    1450  2015/09  30550.0  26800.0  28748.0  30250.0   
3738  현대해상화재보험(주)    1450  2015/12  36600.0  32000.0  34174.0  36050.0   
3739  현대해상화재보험(주)    1450  2016/03  34700.0  31350.0  33470.0  33200.0   
3740  현대해상화재보험(주)    1450  2016/06  32900.0  28400.0  30552.0  29250.0   
3741  현대해상화재보험(주)    1450  2016/09  36850.0  33900.0  35547.0  36250.0   
3742  현대해상화재보험(주)    1450  2016/12  36500.0  31050.0  34048.0  31500.0   
3743  현대해상화재보험(주)    1450  2017/03  34200.0  31950.0  32998.0  34100.0   
3744  현대해상화재보험(주)    1450  2017/06  40100.0  37100.0  38815.0  39900.0   
3745  현대해상화재보험(주)    1450  2017/09  46150.0  42450.0  44345.0  45300.0   
3746  현대해상화재보험(주)    1450  2017/12  48500.0  42450.0  45992.0  47000.0   
3747       휴켐스(주)   69260  2013/03  24600.0  22950.0  23880.0  24050.0   
3748       휴켐스(주)   69260  2013/06  22650.0  17550.0  20642.0  18400.0   
3749       휴켐스(주)   69260  2013/09  23450.0  20800.0  22317.0  22450.0   
3750       휴켐스(주)   69260  2013/12  24800.0  22600.0  23640.0  24000.0   
3751       휴켐스(주)   69260  2014/03  23450.0  21300.0  22569.0  21550.0   
3752       휴켐스(주)   69260  2014/06  24750.0  23100.0  23916.0  23700.0   
3753       휴켐스(주)   69260  2014/09  24600.0  23350.0  23868.0  23600.0   
3754       휴켐스(주)   69260  2014/12  29000.0  24400.0  26579.0  25100.0   
3755       휴켐스(주)   69260  2015/03  26350.0  24500.0  25261.0  25550.0   
3756       휴켐스(주)   69260  2015/06  26150.0  23750.0  24966.0  25000.0   
3757       휴켐스(주)   69260  2015/09  20300.0  18450.0  19418.0  19550.0   
3758       휴켐스(주)   69260  2015/12  17550.0  13950.0  15531.0  15300.0   
3759       휴켐스(주) 

In [6]:
a = pd.merge(finance_info, stock_info, on = ['회사명','거래소코드','거래년월'])

In [7]:
a.columns = ['회사명', '거래소코드', '거래년월', '자산', '자본',
       '이익잉여금', '당기순손익', '미처분이익잉여금', '부채', '최고가', '최저가',
       '산술평균', '종가', '거래량', '거래대금']

In [8]:
a.columns

Index(['회사명', '거래소코드', '거래년월', '자산', '자본', '이익잉여금', '당기순손익', '미처분이익잉여금', '부채',
       '최고가', '최저가', '산술평균', '종가', '거래량', '거래대금'],
      dtype='object')

In [9]:
a1 = a[['거래소코드','자산', '자본', '이익잉여금', '당기순손익', '미처분이익잉여금', '부채', '산술평균','거래량', '거래대금']]

In [10]:
list_a1 = list(set(a1['거래소코드']))

In [11]:
# 거래소코드별로 list에 담음
list_a2 = []
for i in range(len(list_a1)):
    a2 = a1[a1['거래소코드'] == list_a1[i]]
    list_a2.append(a2)

# 정규화 하는 중

In [12]:
len(list_a2)

197

In [13]:
list_a2[0]
# list_a2[0].iloc[0,:] # 1행
# list_a2[0].iloc[:,0] # 1열

거래소코드            자산            자본         이익잉여금         당기순손익  \
1537  96770  1.480850e+10  1.302663e+10  6.823103e+09  8.173240e+07   
1538  96770  1.410206e+10  1.313049e+10  6.933297e+09  1.898033e+08   
1539  96770  1.456802e+10  1.317828e+10  6.979912e+09  2.363522e+08   
1540  96770  1.448669e+10  1.317183e+10  6.975646e+09  2.370324e+08   
1541  96770  1.469631e+10  1.312674e+10  6.933719e+09  2.628077e+08   
1542  96770  1.444226e+10  1.310538e+10  6.909569e+09  2.389124e+08   
1543  96770  1.470866e+10  1.311640e+10  6.927161e+09  2.582192e+08   
1544  96770  1.450860e+10  1.299231e+10  6.809241e+09  1.386168e+08   
1545  96770  1.456197e+10  1.305114e+10  6.868873e+09  6.269085e+07   
1546  96770  1.448717e+10  1.295249e+10  6.763362e+09 -4.683338e+07   
1547  96770  1.460133e+10  1.309917e+10  6.916421e+09  1.064611e+08   
1548  96770  1.447419e+10  1.299653e+10  6.806449e+09 -5.617027e+06   
1549  96770  1.439638e+10  1.259704e+10  6.412482e+09  5.664538e+07   
1550  96770  1.379771e+10  1.247259e+10  6.287295e+09 -6.747146e+07   
1551  96770  1.380280e+10  1.243472e+10  6.250611e+09 -1.050343e+08   
1552  96770  1.356184e+10  1.221076e+10  6.018326e+09 -3.441992e+08   
1553  96770  1.404871e+10  1.216887e+10  5.972608e+09  5.551498e+08   
1554  96770  1.343118e+10  1.209065e+10  5.899798e+09  4.815247e+08   
1555  96770  1.473520e+10  1.325207e+10  7.050603e+09  1.779678e+09   
1556  96770  1.479519e+10  1.308697e+10  6.874224e+09  1.600005e+09   

          미처분이익잉여금            부채      산술평균         거래량          거래대금  
1537  6.527003e+09  1.781878e+09  165300.0   5498416.0  9.117269e+09  
1538  6.637197e+09  9.715725e+08  139000.0   5634742.0  7.786675e+09  
1539  6.683811e+09  1.389733e+09  146306.0   8023427.0  1.170746e+10  
1540  6.679546e+09  1.314866e+09  139925.0   5232655.0  7.339417e+09  
1541  6.607719e+09  1.569563e+09  126357.0   6321598.0  7.891333e+09  
1542  6.583569e+09  1.336876e+09  105295.0  11386608.0  1.196226e+10  
1543  6.601161e+09  1.592261e+09   88884.0   7874282.0  6.955508e+09  
1544  6.483241e+09  1.516290e+09   85424.0   8789276.0  7.481408e+09  
1545  6.542873e+09  1.510826e+09   94923.0  10617301.0  1.009015e+10  
1546  6.437362e+09  1.534678e+09  122000.0   9701678.0  1.185210e+10  
1547  6.590421e+09  1.502153e+09   97875.0   6104656.0  5.976689e+09  
1548  6.480449e+09  1.477660e+09  129738.0   6261273.0  8.140400e+09  
1549  6.041482e+09  1.799343e+09  158636.0   6595082.0  1.044018e+10  
1550  5.916295e+09  1.325123e+09  148357.0   7183476.0  1.051024e+10  
1551  5.879611e+09  1.368083e+09  153684.0   4831357.0  7.480155e+09  
1552  5.647326e+09  1.351076e+09  150881.0   5789378.0  8.750887e+09  
1553  5.578323e+09  1.879838e+09  159881.0   5987315.0  9.558558e+09  
1554  5.505513e+09  1.340528e+09  159100.0   7361740.0  1.170613e+10  
1555  6.656318e+09  1.483129e+09  190714.0   5444648.0  1.037842e+10  
1556  6.479939e+09  1.708216e+09  203789.0   3896788.0  7.931791e+09

In [14]:
from sklearn.preprocessing import MinMaxScaler
mmscaler = MinMaxScaler()

scaling = []
for i in range(len(list_a2)): #len(list_a2) = 197
    a = mmscaler.fit_transform(list_a2[i])
    scaling.append(a)

In [15]:
scaling[0][0] # 거래소코드 자산 자본 이익잉여금 당기순손익 미처분이익잉여금 부채 산술평균 거래량 거래대금

array([0.        , 1.        , 0.80588627, 0.80231277, 0.20054436,
       0.86691969, 0.8921454 , 0.67482786, 0.21384065, 0.52469144])

In [16]:
scaling[0][1]

array([0.        , 0.48709067, 0.89531443, 0.89806612, 0.25142813,
       0.96043921, 0.        , 0.4526338 , 0.23204216, 0.30239133])

In [17]:
scaling[0][1] - scaling[0][0] # 뒤에서 앞을 빼야한다

array([ 0.        , -0.51290933,  0.08942816,  0.09575335,  0.05088377,
        0.09351953, -0.8921454 , -0.22219406,  0.01820151, -0.22230011])

In [18]:
# 정규화 한거 전부 담음

# 0:거래소코드 1:자산 2:자본 3:이익잉여금 4:당기순손익 5:미처분이익잉여금 6:부채 7:산술평균 8:거래량 9:거래대금

list_a3 = []
for i in range(len(list_a2)):
    for j in range(len(list_a2[i])-1):
        a = scaling[i][j+1] - scaling[i][j]
        list_a3.append(a)

# 주가 상승=> 1 //  주가 하락 => 0 으로 변환

In [19]:
for i in range(len(list_a3)): # len(list_a3) : 3511
    if list_a3[i][7] <= 0:
        list_a3[i][7] = 0
    else:
        list_a3[i][7] = 1

# 추후에 상승률을 기준으로 세금을 고려해서 1.03% 이상 상승할때에만 주가 상승으로 반영하자
# 일단은 되는지만 보자

In [20]:
list_a3[0] # 주가가 하락해서 0으로 변경됨

array([ 0.        , -0.51290933,  0.08942816,  0.09575335,  0.05088377,
        0.09351953, -0.8921454 ,  0.        ,  0.01820151, -0.22230011])

In [21]:
df_scaling = pd.DataFrame(list_a3)

In [22]:
df_scaling.head(2)

0         1         2         3         4         5         6    7  \
0  0.0 -0.512909  0.089428  0.095753  0.050884  0.093520 -0.892145  0.0   
1  0.0  0.338303  0.041149  0.040506  0.021917  0.039561  0.460395  1.0   

          8         9  
0  0.018202 -0.222300  
1  0.318924  0.655039

In [23]:
df_x = df_scaling.drop([0,7],1) # 종목코드, 주가변화 열 제거
df_x.head()

1         2         3         4         5         6         8  \
0 -0.512909  0.089428  0.095753  0.050884  0.093520 -0.892145  0.018202   
1  0.338303  0.041149  0.040506  0.021917  0.039561  0.460395  0.318924   
2 -0.059043 -0.005557 -0.003707  0.000320 -0.003620 -0.082429 -0.372609   
3  0.152188 -0.038819 -0.036433  0.012136 -0.060958  0.280422  0.145390   
4 -0.184450 -0.018391 -0.020985 -0.011251 -0.020496 -0.256189  0.676253   

          9  
0 -0.222300  
1  0.655039  
2 -0.729761  
3  0.092208  
4  0.680124

In [24]:
df_y = df_scaling[7] # 주가변화 열 추출
df_y = df_y.astype(int) # 원핫인코딩 떄문에 인트로 변경
df_y.head()

0    0
1    1
2    0
3    0
4    0
Name: 7, dtype: int32

# 샤비어 초기화 함수

In [25]:
def xavier_init(n_inputs, n_outputs, uniform=True):
    if uniform:
        # 6 was used in the paper.
        init_range = tf.sqrt(6.0 / (n_inputs + n_outputs))
        return tf.random_uniform_initializer(-init_range, init_range)
    else:
        # 3 gives us approximately the same limints as above since this repicks
        # values greater than 2 standard deviations from the mean.
        stddev = tf.sqrt(3.0 / (n_inputs + n_outputs))
        return tf.truncated_normal_initializer(stddev=stddev)

# 레이어 추가 안한 모델

In [26]:
'''
# Review : Learning rate and Evaluation
import tensorflow as tf
import random
import matplotlib.pyplot as plt

tf.reset_default_graph()

x_data = df_x
sess = tf.Session()
y_data = tf.one_hot(df_y, depth = 2).eval(session=sess)
y_data = tf.reshape(y_data, shape=[-1,2]).eval(session=sess)
print(y_data)
tf.set_random_seed(888)  # reproducibility


# parameters
learning_rate = 0.001
placeholder_num = len(df_x.columns)

X = tf.placeholder(tf.float32, [None, placeholder_num])
Y = tf.placeholder(tf.float32, [None, 2])

W1 = tf.get_variable("W1", shape=[placeholder_num, 2],
                     initializer=xavier_init(placeholder_num, 2))
b1 = tf.Variable(tf.random_normal([2]))

hypothesis = tf.matmul(X, W1) + b1

# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
'''

'\n# Review : Learning rate and Evaluation\nimport tensorflow as tf\nimport random\nimport matplotlib.pyplot as plt\n\ntf.reset_default_graph()\n\nx_data = df_x\nsess = tf.Session()\ny_data = tf.one_hot(df_y, depth = 2).eval(session=sess)\ny_data = tf.reshape(y_data, shape=[-1,2]).eval(session=sess)\nprint(y_data)\ntf.set_random_seed(888)  # reproducibility\n\n\n# parameters\nlearning_rate = 0.001\nplaceholder_num = len(df_x.columns)\n\nX = tf.placeholder(tf.float32, [None, placeholder_num])\nY = tf.placeholder(tf.float32, [None, 2])\n\nW1 = tf.get_variable("W1", shape=[placeholder_num, 2],\n                     initializer=xavier_init(placeholder_num, 2))\nb1 = tf.Variable(tf.random_normal([2]))\n\nhypothesis = tf.matmul(X, W1) + b1\n\n# define cost/loss & optimizer\ncost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(\n    logits=hypothesis, labels=Y))\noptimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)\ncorrect_prediction = tf.equal(tf.argmax(hy

In [27]:
'''
# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(10000):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0 or step < 100:
        loss, acc = sess.run([cost, accuracy], feed_dict={
                             X: x_data, Y: y_data})
        print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(
            step, loss, acc))
'''

'\n# Launch the graph in a session.\nsess = tf.Session()\n\n# Initializes global variables in the graph.\nsess.run(tf.global_variables_initializer())\n\nfor step in range(10000):\n    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})\n    if step % 100 == 0 or step < 100:\n        loss, acc = sess.run([cost, accuracy], feed_dict={\n                             X: x_data, Y: y_data})\n        print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(\n            step, loss, acc))\n'

# 레이어 추가 모델

In [29]:

# Review : Learning rate and Evaluation
import tensorflow as tf
import random
import matplotlib.pyplot as plt

tf.reset_default_graph()

placeholder_num = len(df_x.columns)


x_data = df_x
sess = tf.Session()
y_data = tf.one_hot(df_y, depth = 2).eval(session=sess)
y_data = tf.reshape(y_data, shape=[-1,2]).eval(session=sess)
print(y_data)
tf.set_random_seed(777)  # reproducibility



# parameters
learning_rate = 0.001



X = tf.placeholder(tf.float32, [None, placeholder_num])
Y = tf.placeholder(tf.float32, [None, 2])
keep_prob = tf.placeholder(tf.float32)


W1 = tf.get_variable("W1", shape=[placeholder_num, 32], initializer=tf.contrib.layers.xavier_initializer())
b1 = tf.Variable(tf.random_normal([32]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L1 = tf.nn.dropout(L1, keep_prob=keep_prob)


W2 = tf.get_variable("W2", shape=[32, 64], initializer=tf.contrib.layers.xavier_initializer())
b2 = tf.Variable(tf.random_normal([64]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L2 = tf.nn.dropout(L2, keep_prob=keep_prob)

W3 = tf.get_variable("W3", shape=[64, 64], initializer=tf.contrib.layers.xavier_initializer())
b3 = tf.Variable(tf.random_normal([64]))
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
L3 = tf.nn.dropout(L3, keep_prob=keep_prob)


W4 = tf.get_variable("W4", shape=[64, 64], initializer=tf.contrib.layers.xavier_initializer())
b4 = tf.Variable(tf.random_normal([64]))
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)
L4 = tf.nn.dropout(L4, keep_prob=keep_prob)


W5 = tf.get_variable("W5", shape=[64, 2], initializer=tf.contrib.layers.xavier_initializer())
b5 = tf.Variable(tf.random_normal([2]))
L5 = tf.nn.relu(tf.matmul(L4, W5) + b5)

hypothesis = tf.matmul(L4, W5) + b5


# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

C:\Python\Anaconda3-52\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [32]:
# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(10001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data, keep_prob: 0.7})
    if step % 1000 == 0 or step < 100:
        loss, acc = sess.run([cost, accuracy], feed_dict={
                             X: x_data, Y: y_data, keep_prob: 0.7})
        print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(
            step, loss, acc))

Step:     0, 	 Loss: 0.892, 	 Acc: 50.58%
Step:     1, 	 Loss: 0.893, 	 Acc: 49.67%
Step:     2, 	 Loss: 0.865, 	 Acc: 50.19%
Step:     3, 	 Loss: 0.836, 	 Acc: 50.61%
Step:     4, 	 Loss: 0.835, 	 Acc: 49.59%
Step:     5, 	 Loss: 0.832, 	 Acc: 48.42%
Step:     6, 	 Loss: 0.815, 	 Acc: 49.73%
Step:     7, 	 Loss: 0.782, 	 Acc: 51.84%
Step:     8, 	 Loss: 0.799, 	 Acc: 48.93%
Step:     9, 	 Loss: 0.787, 	 Acc: 49.13%
Step:    10, 	 Loss: 0.774, 	 Acc: 49.05%
Step:    11, 	 Loss: 0.783, 	 Acc: 48.99%
Step:    12, 	 Loss: 0.754, 	 Acc: 50.36%
Step:    13, 	 Loss: 0.753, 	 Acc: 50.38%
Step:    14, 	 Loss: 0.744, 	 Acc: 51.47%
Step:    15, 	 Loss: 0.742, 	 Acc: 50.27%
Step:    16, 	 Loss: 0.732, 	 Acc: 51.81%
Step:    17, 	 Loss: 0.742, 	 Acc: 49.62%
Step:    18, 	 Loss: 0.739, 	 Acc: 49.64%
Step:    19, 	 Loss: 0.733, 	 Acc: 49.30%
Step:    20, 	 Loss: 0.725, 	 Acc: 50.38%
Step:    21, 	 Loss: 0.728, 	 Acc: 48.73%
Step:    22, 	 Loss: 0.727, 	 Acc: 49.96%
Step:    23, 	 Loss: 0.724, 	 Acc: